Resources:
  VPC1lab:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Name
         Value: VPC1Cloudformation
  IGWVPC1CloudFormation:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: IGWVPC1CloudFormation
  IGWAttach:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC1lab
      InternetGatewayId: !Ref IGWVPC1CloudFormation
  PublicSubnetVPC1CloudFormation:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: "us-east-2a"
      Tags:
        - Key: Name
          Value: PublicSubnetVPC1CloudFormation
      VpcId: !Ref VPC1lab
  PrivateSubnetVPC1CloudFormation:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: "us-east-2b"
      Tags:
        - Key: Name
          Value: PrivateSubnetVPC1CloudFormation
      VpcId: !Ref VPC1lab
  PublicRouteTableVPC1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: VPC1lab
      Tags:
      - Key: Name
        Value: PublicRouteTableVPC1
  RoutetoInternet:
    Type: AWS::EC2::Route
    DependsOn: IGWAttach
    Properties:
       RouteTableId:
         Ref: PublicRouteTableVPC1
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: IGWVPC1CloudFormation
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTableVPC1
      SubnetId: !Ref PublicSubnetVPC1CloudFormation

