AWSTemplateFormatVersion: "2010-09-09"

Resources:
  VPC1lab:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Name
         Value: VPC1Cloudformation
  IGWVPC1CloudFormation:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: IGWVPC1CloudFormation
  IGWAttach:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC1lab
      InternetGatewayId: !Ref IGWVPC1CloudFormation
  PublicSubnetVPC1CloudFormation:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: "us-east-2a"
      Tags:
        - Key: Name
          Value: PublicSubnetVPC1CloudFormation
      VpcId: !Ref VPC1lab
  PrivateSubnetVPC1CloudFormation:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: "us-east-2b"
      Tags:
        - Key: Name
          Value: PrivateSubnetVPC1CloudFormation
      VpcId: !Ref VPC1lab
  PublicRouteTableVPC1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: VPC1lab
      Tags:
      - Key: Name
        Value: PublicRouteTableVPC1
  RoutetoInternet:
    Type: AWS::EC2::Route
    DependsOn: IGWAttach
    Properties:
       RouteTableId:
         Ref: PublicRouteTableVPC1
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: IGWVPC1CloudFormation
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTableVPC1
      SubnetId: !Ref PublicSubnetVPC1CloudFormation

  PublicInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.nano
      ImageId: ami-00bf61217e296b409
      KeyName: test-1-Nov-2018
      SecurityGroupIds: 
      - !Ref PublicInstanceSG
      SubnetId: !Ref PublicSubnetVPC1CloudFormation
      Tags:
        - Key: Name
          Value: PublicInstance

  PublicInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Public Instance
      GroupName: PublicSG     
      VpcId: !Ref VPC1lab
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.nano
      ImageId: ami-00bf61217e296b409
      KeyName: test-1-Nov-2018
      SubnetId: !Ref PrivateSubnetVPC1CloudFormation
      Tags:
        - Key: Name
          Value: PrivateInstance